// Code generated by Kitex v0.5.1. DO NOT EDIT.
package artworkservice

import (
	artwork "github.com/IPAM/kitex_gen/artwork"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler artwork.ArtworkService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
