// Code generated by hertz generator.

package main

import (
	"github.com/IPAM/server/api/dboperation"
	"github.com/IPAM/server/api/mw"
	"github.com/IPAM/server/api/rpc"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	Co "github.com/hertz-contrib/cors"
	"time"
)

func Init() {
	rpc.Init()
	mw.InitJWT()
	// hlog init
	dboperation.Dbinit()
	hlog.SetLevel(hlog.LevelInfo)
}

func main() {
	Init()
	h := server.New(
		server.WithHostPorts(":8080"),
		server.WithHandleMethodNotAllowed(true), // coordinate with NoMethod
		server.WithMaxRequestBodySize(400*1024*1024),
	)
	h.Use(Co.New(Co.Config{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"PUT", "PATCH", "GET", "POST"},
		AllowHeaders:     []string{"*"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))
	register(h)
	h.Spin()
}
